![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [5]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

2.2.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here

print(f"array_1: {np.zeros(10, dtype=int)}")
print(f"array_2: {np.array([0] * 10)}")

array_1: [0 0 0 0 0 0 0 0 0 0]
array_2: [0 0 0 0 0 0 0 0 0 0]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [3]:
# your code goes here

print(f"array_1: {np.arange(10,50)}")
print(f"array_2: {np.array(list(range(10,50)))}")
print(f"array_3: {np.array(list(map(lambda x : x, range(10,50))))}")

array_1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
array_2: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
array_3: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
# your code goes here
print(f"matrix_1:\n{np.array([[1,1],[1,1]])}")
print(f"matrix_2:\n{np.array([np.ones(2, dtype=int),np.ones(2, dtype=int)])}")
print(f"matrix_3:\n{np.ones([2,2],dtype=int)}")

matrix_1:
[[1 1]
 [1 1]]
matrix_2:
[[1 1]
 [1 1]]
matrix_3:
[[1 1]
 [1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [10]:
# your code goes here
print(f"matrix_1: {np.array([[1,1],[1,1],[1,1]], dtype=float)}")
print(f"matrix_2: {np.array([np.ones(2, dtype=float),np.ones(2, dtype=float),np.ones(2, dtype=float)])}")
print(f"matrix_3: {np.ones([3,2],dtype=float)}")

matrix_1: [[1. 1.]
 [1. 1.]
 [1. 1.]]
matrix_2: [[1. 1.]
 [1. 1.]
 [1. 1.]]
matrix_3: [[1. 1.]
 [1. 1.]
 [1. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [11]:
# your code goes here
shape = 5
x  = np.arange(shape, dtype=int)
print(f"x: {x}")
print(f"new_1: {np.ones(x.shape,dtype=int)}")
print(f"new_2:{np.ones_like(x)}")

x: [0 1 2 3 4]
new_1: [1 1 1 1 1]
new_2:[1 1 1 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [12]:
# your code goes here
shape = 5
x  = np.arange(shape, dtype=int)
print(f"x: {x}")
print(f"new_1: {np.zeros(x.shape,dtype=int)}")
print(f"new_2: {np.zeros_like(x)}")

x: [0 1 2 3 4]
new_1: [0 0 0 0 0]
new_2: [0 0 0 0 0]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [13]:
# your code goes here
print(f"matrix\n{np.ones([4,4], dtype=int) * 5}")

matrix
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [69]:
# your code goes here
x = np.array([[6,3,8], [6,2,3]], dtype=int)
print(f"x:\n{x}")
copy_x = np.ones_like(x) * 7
print(f"copy_x:\n{copy_x}")

x:
[[6 3 8]
 [6 2 3]]
copy_x:
[[7 7 7]
 [7 7 7]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [82]:
# your code goes here
n = 5
zeros = np.zeros([n,n])
for i in range(0,n):
    for j in range(0,n):
        if j == i :
            zeros[i,j]=1

print(f"manual:\n{zeros}")
print(f"eye:\n{np.eye(n)}")
print(f"identity:\n{np.identity(n)}")


manual:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
eye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
identity:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [101]:
# your code goes here
import random
x = lambda: random.randint(1,10)
print(f"array_random: {np.array([x(),x(),x()])}")
print(f"np.random: {np.random.randint(10, size=3)}")

array_random: [7 4 8]
np.random: [6 1 0]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [110]:
# your code goes here

print(f"np.random: {np.random.randn(3,3,3)}")

np.random: [[[ 1.63167209 -1.68598908 -1.16452933]
  [-0.84147627  1.26436915 -1.10136599]
  [-0.20933908  0.63443388 -1.32541663]]

 [[ 1.05234302 -1.63916143  0.33422725]
  [ 1.1915255   1.33629173 -1.40504156]
  [ 1.17962724  0.07699839 -1.69416485]]

 [[ 0.70325046  0.4985866  -0.32400154]
  [-0.820423   -1.6371848   0.74215127]
  [ 0.6699689  -1.23119399  0.08846663]]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [ ]:
# your code goes here
x = [1,2,3]
print(f"{x}: {type(x)}")
y = np.array(x)
print(f"{y}: {type(y)}")

[1, 2, 3]: <class 'list'>
[1 2 3]: <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [126]:
# your code goes here
x = np.array([1,2,3], dtype=int)
y = np.copy(x)
y2 = x.copy()

print(f"x:{x} id:{id(x)} {type(x)}:: y{y} {id(y)} {type(y)}")
print(f"x:{x} id:{id(x)} {type(x)}:: y{y2} {id(y2)} {type(y2)}")

x:[1 2 3] id:1816769289104 <class 'numpy.ndarray'>:: y[1 2 3] 1816769286992 <class 'numpy.ndarray'>
x:[1 2 3] id:1816769289104 <class 'numpy.ndarray'>:: y[1 2 3] 1816769285168 <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [125]:
# your code goes here
print(f"{np.arange(start=1, stop=11, step=1)}")

[ 1  2  3  4  5  6  7  8  9 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [137]:
# your code goes here
print(f"{np.arange(start=1, stop=11, step=2)}")

numbers = np.arange(start=1, stop=11, step=1)
odd_numbers = numbers[numbers % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
[1 3 5 7 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [149]:
# your code goes here
numbers = np.arange(start=1, stop=11, step=1)
print(f"numbers: {numbers[::-1]}")

numbers: [10  9  8  7  6  5  4  3  2  1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [45]:
# your code goes here
#prueba con lambda
import random
x = lambda: random.randint(0,8)
lista = lambda: [x(),x(),x()]
print(f"lambda:\n{np.array([lista(),lista(),lista()])}")

print(f"reshape:\n{np.arange(9).reshape(3,3)}")

lambda:
[[1 2 4]
 [6 0 5]
 [1 5 3]]
reshape:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [65]:
# your code goes here
z = np.ones((8,8))
print(z)
print(f"size: {z.size}")
print(f"items size: {z.itemsize}")
print(f"memori size: {(z.size * z.itemsize)} bytes")
print(f"Memory size: {(z.size * z.itemsize) / 1_000_000} Megabytes")

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
size: 64
items size: 8
memori size: 512 bytes
Memory size: 0.000512 Megabytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [75]:
# your code goes here

x = np.arange(1,10)
print(f" first element: {x[0]}")

x = np.array(['A','B','C','D','E'])
print(f" first element: {x[0]}")

 first element: 1
 first element: A


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [112]:
# your code goes here
x = np.array(['A','B','C','D','E'])
print(f" last element: {x[-1:]}")
print(f" last element: {x[-1]}")
print(f" last element: {x[x.shape[0]-1]}")
print(f" last element: {x[len(x)-1]}")

 last element: ['E']
 last element: E
 last element: E
 last element: E


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [111]:
# your code goes here
x = np.array(['A','B','C','D','E'])
# print(f" last element: {x[-3:]}")
print(f" three elements: {x[:3]}")
print(f" three elements: {x[0:3]}")

 three elements: ['A' 'B' 'C']
 three elements: ['A' 'B' 'C']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here
x = np.array(['A','B','C','D','E','F','G'])
print(f"middle lements(slicing): {(x[1:-1])}")

middle lements(slicing): ['B' 'C' 'D' 'E' 'F']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [133]:
# your code goes here
x = np.array(['A','B','C','D','E','F','G'])
print(f"reverse lements(slicing): {(x[::-1])}")

reverse lements(slicing): ['G' 'F' 'E' 'D' 'C' 'B' 'A']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [ ]:
# your code goes here
x = np.array(['A','B','C','D','E','F','G'])
print(f"odd position(slicing): {(x[::2])}") # cada dos elementos

odd position(slicing): ['A' 'C' 'E' 'G']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [ ]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f"first row elements:\n{x[0]}")

first row:
[1 2 3 4]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [4]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f"last row elements:\n{x[-1]}")

last row elements:
[13 14 15 16]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [15]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'first element(array): {x[0][0]}')
print(f'first element(matrix): {x[0,0]}')

first element(array): 1
first element(matrix): 1


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [16]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'last element(array): {x[-1][-1]}')
print(f'last element(matrix): {x[-1,-1]}')

last element(array): 16
last element(matrix): 16


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [ ]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'middle row: {x[1:-1][1:-1]}') # la matriz no es posible tratarla como un array normal por que se generan dos arrays independientes 
print(f'middle row:\n{x[1:-1, 1:-1]}')

middle row: []
middle row:
[[ 5  6  7  8]
 [ 9 10 11 12]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [17]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'two elements:\n{x[:2,:2]}')

two elements:
[[1 2]
 [5 6]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [8]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'last two elements:\n{x[-2:,-2:]}')

last two elements:
[[11 12]
 [15 16]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [193]:
# your code goes here
x = [-5, -3, 0, 10, 40]
print(f"original: {x}")
x2 = np.float64(x)
print(f"np.float64: {x2}")
x3 = np.array(x, dtype=float)
print(f"np dtype: {x3}")

original: [-5, -3, 0, 10, 40]
np.float64: [-5. -3.  0. 10. 40.]
np dtype: [-5. -3.  0. 10. 40.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [197]:
# your code goes here
x = np.array([-5, -3, 0, 10, 40])
print(f"reverse: {x[::-1]}")

reverse: [40 10  0 -3 -5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [201]:
# your code goes here
x = np.array([-5, -3, 0, 10, 40])
print(f"order: {np.sort(x)}")

order: [-5 -3  0 10 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [203]:
# your code goes here
x = np.array([-5, -3, 0, 10, 40])
x[4] = 1
print(f"set 1: {x}")

set 1: [-5 -3  0 10  1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [10]:
# your code goes here
x = np.array([2,50,-5, -3, 0, 10, 80, 50])
print(f"original: {x}")
indexs = np.where(x == 50)
for index in indexs[0]:
    print(f"index to change: {index}")
x[indexs] = 40
print(f"change: {x}")

original: [ 2 50 -5 -3  0 10 80 50]
index to change: 1
index to change: 7
change: [ 2 40 -5 -3  0 10 80 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [225]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'original:\n {x}')
x[-1] = np.ones_like(x[-1])
print(f'last change elements:\n {x}')

original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
last change elements:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [228]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'original:\n {x}')
x[-1,-1] = 0
print(f'last change elements:\n {x}')

original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
last change elements:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [ ]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(f'original:\n {x}')

print(f'add 5 the each elements:\n {x+5}')

original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
add 5 the each elements:
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


<div>
    <p>Basic logic operators numpy</p>
</div>
<table style="width:100%; border: 1px solid black; border-collapse: collapse;">
    <tr>
        <th style="text-align: center; border: 1px solid black; padding: 8px;">Operator</th>
        <th style="text-align: center; border: 1px solid black; padding: 8px;">Function Numpy</th>
        <th style="text-align: center; border: 1px solid black; padding: 8px;">Symbols Python</th>
        <th style="text-align: center; border: 1px solid black; padding: 8px;">Example with Mask</th>
    </tr>
    <tr>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">AND</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">np.logical_and()</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">&</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">(arr > 2) & (arr < 5)</td>
    </tr>
    <tr>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">OR</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">np.logical_or()</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">|</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">(arr == 3) | (arr == 5)</td>
    </tr>
    <tr>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">NOT</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">np.logical_not()</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">~</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">~(arr == 0)</td>
    </tr>
    <tr>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">XOR</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">np.logical_xor()</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">-</td>
        <td style="text-align: center; border: 1px solid black; padding: 8px;">np.logical_xor(arr > 1, arr < 4)</td>
    </tr>
</table>

### Given the X numpy array, make a mask showing negative elements

In [32]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array:\n{x}")
mask_array = x < 0
print(f"mask negative elements:\n{mask_array}")

array:
[-1  2  0 -4  5  6  0  0 -9 10]
mask negative elements:
[ True False False  True False False False False  True False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [33]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array:\n{x}")
mask_array = x < 0
print(f"negative elements with mask:\n{x[mask_array]}")
indexs = np.where(x < 0)
print(f"negative elements with indexs:\n{x[indexs]}")

array:
[-1  2  0 -4  5  6  0  0 -9 10]
negative elements with mask:
[-1 -4 -9]
negative elements with indexs:
[-1 -4 -9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [34]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array:\n{x}")
mask_array = x > 5
print(f"elements with mask:\n{x[mask_array]}")
indexs = np.where(x > 5)
print(f"elements with indexs:\n{x[indexs]}")

array:
[-1  2  0 -4  5  6  0  0 -9 10]
elements with mask:
[ 6 10]
elements with indexs:
[ 6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [35]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array:\n{x}")
median = np.median(x)
mask_array = x > median
print(f"elements with np.median() ({median}):\n{x[mask_array]}")
mask_array = x > x.mean()
print(f"elements with mean() ({x.mean()}):\n{x[mask_array]}")

array:
[-1  2  0 -4  5  6  0  0 -9 10]
elements with np.median() (0.0):
[ 2  5  6 10]
elements with mean() (0.9):
[ 2  5  6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [39]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array:\n{x}")
mask_array = (x == 2) | (x == 10)
print(f"mask:\n{mask_array}")
print(f"elements with logical operators:\n{x[mask_array]}")

array:
[-1  2  0 -4  5  6  0  0 -9 10]
mask:
[False  True False False False False False False False  True]
elements with logical operators:
[ 2 10]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [50]:
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array with zeros:\n{x}")
print(f"are all elements non-zero?:\n{np.all(x != 0)}")

print("---------------")
# changing values ​​from zeros to eights for testing
mask = x == 0
x[mask] = 8
print(f"array without zeros:\n{x}")
print(f"are all elements non-zero?:\n{np.all(x != 0)}")

array with zeros:
[-1  2  0 -4  5  6  0  0 -9 10]
are all elements non-zero?:
False
---------------
array without zeros:
[-1  2  8 -4  5  6  8  8 -9 10]
are all elements non-zero?:
True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [52]:
# your code goes here
# your code goes here
x = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(f"array with zeros:\n{x}")
print(f"contains elements in zero?:\n{np.any(x == 0)}")

print("---------------")
# changing values ​​from zeros to eights for testing
mask = x == 0
x[mask] = 8
print(f"array without zeros:\n{x}")
print(f"contains elements in zero:\n{np.any(x == 0)}")

array with zeros:
[-1  2  0 -4  5  6  0  0 -9 10]
contains elements in zero?:
True
---------------
array without zeros:
[-1  2  8 -4  5  6  8  8 -9 10]
contains elements in zero:
False


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [55]:
# your code goes here
x = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
print(f"Sum: {x.sum()}")
print(f"Sum np.sum: {np.sum(x)}")

Sum: 43
Sum np.sum: 43


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [60]:
# your code goes here
x = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
print(f"Sum: {x.sum()}")
print(f"n: {x.shape[0]}")
print(f"mean (calculate): {np.sum(x)/x.shape[0]}")
print(f"mean (np.mean): {x.mean()}")

Sum: 43
n: 9
mean (calculate): 4.777777777777778
mean (np.mean): 4.777777777777778


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [64]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(f"matrix:\n{x}")
print(f"Sum of its columns (axis=0): {x.sum(axis=0)}")

matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of its columns (axis=0): [28 32 36 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [67]:
# your code goes here
x = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(f"matrix:\n{x}")
print(f"sum of its columns (axis=1): {x.sum(axis=1)}")
print(f"mean value of its rows (mean): {x.mean(axis=1)}")

matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of its columns (axis=1): [10 26 42 58]
mean value of its rows (mean): [ 2.5  6.5 10.5 14.5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [ ]:
# your code goes here
x = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
print(f"max value: {x.max()}")

max value: 10
1


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Exercises taken from the video tutorials

In [6]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [63]:
a = np.arange(10000)
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1.01 ms


np.int64(333283335000)

In [59]:
l = list(range(10000))
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 995 μs


333283335000